ARG BASE
FROM $BASE

ARG AUTHOR
ARG VERSION
LABEL maintainer=$AUTHOR version=$VERSION

ENV GOPROXY=https://goproxy.cn
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH

RUN apt update -y && \
apt install -y curl wget xz-utils git && \
mkdir -p /tmp/loongarch64/gcc && \
curl https://cache.wodcloud.com/vscode/loongarch64/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.1.tar.xz > /tmp/loongarch64/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.1.tar.xz && \
tar -xvf /tmp/loongarch64/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.1.tar.xz -C /tmp/loongarch64/gcc && \
cp -r /tmp/loongarch64/gcc/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.1/* /usr/ && \
mkdir -p /tmp/loongarch64/golang && \
curl https://cache.wodcloud.com/vscode/loongarch64/go1.20.2.linux-amd64.tar.gz > /tmp/loongarch64/go1.20.2.linux-amd64.tar.gz && \
tar xzvf /tmp/loongarch64/go1.20.2.linux-amd64.tar.gz -C /tmp/loongarch64/golang && \
mv /tmp/loongarch64/golang/go /usr/local && \
rm -rf /tmp/loongarch64 && \
apt install -y rsync build-essential crossbuild-essential-arm64 crossbuild-essential-ppc64el crossbuild-essential-mips64el
