name: Build Golang 1.23 Images

on:
  push:
    branches:
      - release-1.23
  workflow_dispatch: # 允许手动触发

env:
  REGISTRY_ALIYUN: registry.cn-qingdao.aliyuncs.com
  GOLANG_VERSION: 1.23.9
  GOLANG_MAJOR_VERSION: 1.23
  LOONGIX_GCC: gnu-toolchain-8.3
  LOONGIX_GCC_VERSION: rc1.6

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_ALIYUN }}
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY_ALIYUN }}/wod/golang:${{ env.GOLANG_VERSION }}-loongnix
            ${{ env.REGISTRY_ALIYUN }}/wod/golang:${{ env.GOLANG_MAJOR_VERSION }}-loongnix
          build-args: |
            BASE="debian:bullseye"
            VERSION="${{ env.GOLANG_MAJOR_VERSION }}"
            GO_VERSION="${{ env.GOLANG_VERSION }}"
            LOONGIX_GCC="${{ env.LOONGIX_GCC }}"
            LOONGIX_GCC_VERSION="${{ env.LOONGIX_GCC_VERSION }}"
          provenance: false
          sbom: false
